hw1_20161622: main.o
# 	gcc -Wall -o hw1_20161622 main.o
	arm-none-linux-gnueabi-gcc -static -o hw1_20161622 main.o
main.o: main.c main.h
#	gcc -Wall -c main.c -o main.o
	arm-none-linux-gnueabi-gcc -c main.c -o main.o
clean:
	-rm *.o
	-rm hw1_20161622
