/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_blackjack_MainActivity_DriverThread */

#ifndef _Included_com_example_blackjack_MainActivity_DriverThread
#define _Included_com_example_blackjack_MainActivity_DriverThread
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_blackjack_MainActivity_DriverThread_MIN_PRIORITY
#define com_example_blackjack_MainActivity_DriverThread_MIN_PRIORITY 1L
#undef com_example_blackjack_MainActivity_DriverThread_NORM_PRIORITY
#define com_example_blackjack_MainActivity_DriverThread_NORM_PRIORITY 5L
#undef com_example_blackjack_MainActivity_DriverThread_MAX_PRIORITY
#define com_example_blackjack_MainActivity_DriverThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
