/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_blackjack_MainActivity */

#ifndef _Included_com_example_blackjack_MainActivity
#define _Included_com_example_blackjack_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_blackjack_MainActivity
 * Method:    driverOpen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_blackjack_MainActivity_driverOpen
  (JNIEnv *, jobject);

/*
 * Class:     com_example_blackjack_MainActivity
 * Method:    driverClose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_blackjack_MainActivity_driverClose
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_blackjack_MainActivity
 * Method:    getDealerData
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_blackjack_MainActivity_getDealerData
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
